#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    departureLocationCode:
      type: string
      example: "2024-04-30T18:41:41.090Z"    
    fromLocation:
      type: string
      example: "BEN-SG" 
    toLocation:
      type: string
      example: "KLG-MY" 
    availableSeats:
      type: number
      example: 50